### ISSUE TITLE
Modules pattern

### ISSUE THREAD

**Issue by amouly** [saulmm/Avengers#2]
Why you are not using the module-oriented pattern for this project? I mean, on your previous project, you divided each part of the MVP pattern on different Java modules. That pattern was very useful I think. Any reason for changing this approach? Thanks.

**Comment by amouly** [comment]
@saulmm ?

**Comment by saulmm** [comment]
Initially, the idea of not moving the layers in modules was to make it more understandable to understand how Dagger2 works, since I think the learning curve is quite high. On the other hand, do not rule wean layers in modules and divide evolution of the project in git tags.

Thanks!
