### ISSUE TITLE
onStart collision between Presenter and Subscriber

### ISSUE THREAD

**Issue by fasteque** [saulmm/Avengers#4]
`AvengerDetailPresenter` extends `Subscriber` and implements `Presenter` but both of them have an `onStart()` method.

In your implementation the method is empty but if you put some code in it could have some unexpected behaviours.

**Comment by fasteque** [comment]
Since the second part focusing on RxJava, the code has been refactored (`AvengerDetailPresenter` does not extend `Subscriber` anymore), so this issue does not apply anymore.

**Comment by saulmm** [comment]
thank you @fasteque, a big release is coming
