### ISSUE TITLE
Crash on rotation

### ISSUE THREAD

**Issue by feresr** [saulmm/Avengers#7]
I was trying to see how you solved RxAndroid + Configuration changes but the app crashed when I tilted my phone. (in both branches, master and fix_load_more_characters_issue)
Here's the stacktrace 

> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{saulmm.avengers/saulmm.avengers.views.activities.AvengersListActivity}: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ProgressBar$SavedState
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread.-wrap15(ActivityThread.java)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:  Caused by: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ProgressBar$SavedState
> 10-14 11:41:16.785 15543-15543/saulmm.avengers E/AndroidRuntime:     at android.widget.ProgressBar.onRestoreInstanceState(ProgressBar.java:1824)

**Comment by saulmm** [comment]
Will solve in incoming releases -> https://github.com/saulmm/Avengers/issues/22

**Comment by feresr** [comment]
Thanks, I've solved this using the approach on this repo https://github.com/android10/Android-CleanArchitecture
I've read that the Mosby framework also provides a solution to it. Haven't tested it myself though.
http://hannesdorfmann.com/android/mosby/

**Comment by saulmm** [comment]
Fernando has a nice approach, good choice. Thanks for the link! Will read carefully.
