### ISSUE TITLE
Crash when selecting year in dialog

### ISSUE THREAD

**Issue by SnakeEys** [saulmm/Avengers#8]
Hi
When I was trying to filter by comic year then it crashed with a NullPointerException, and continuing crashed again with a ClassCastException.

Here are the specific logs:
java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Subscription rx.Observable.subscribe(rx.functions.Action1)' on a null object reference
at saulmm.avengers.mvp.presenters.AvengerDetailPresenter.onItemSelected(AvengerDetailPresenter.java:148)

Unable to start activity ComponentInfo{saulmm.avengers/saulmm.avengers.views.activities.AvengersListActivity}: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ProgressBar$SavedState.

**Comment by saulmm** [comment]
Implementation changed for the next release, Thanks!
